### ISSUE TITLE
Failed to activate the snippets-plus package

### ISSUE THREAD

**Issue by aminya** [Aerijo/snippets-plus#1]
[Enter steps to reproduce:]

1. Install

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [snippets-plus](https://github.com/Aerijo/snippets-plus) package 0.10.0

### Stack Trace

Failed to activate the snippets-plus package

```
At undefined is not iterable (cannot read property Symbol(Symbol.iterator))

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at SnippetsPlus.onDisabledSnippetPackagesDidChange (/packages/snippets-plus/lib/snippets-plus.js:407:27)
    at /packages/snippets-plus/lib/snippets-plus.js:66:14
    at Config.observeKeyPath (<embedded>:11:334919)
    at Config.observe (<embedded>:11:329401)
    at SnippetsPlus.activate (/packages/snippets-plus/lib/snippets-plus.js:65:19)
    at SnippetsPlusPackage.activate (/packages/snippets-plus/lib/main.js:16:23)
    at Package.activateNow (<embedded>:11:3296775)
    at <embedded>:11:3296187
    at Package.measure (<embedded>:11:3293797)
    at <embedded>:11:3296047
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3295990)
    at PackageManager.activatePackage (<embedded>:11:382943)
    at <embedded>:11:926825
    at r (<embedded>:11:921431)
    at n (<embedded>:14:1063434)
    at ChildProcess.<anonymous> (<embedded>:14:1063640)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)

```

### Commands

```
```

**Comment by Aerijo** [comment]
Should be fixed in 0.10.1
